export interface ChatMessages {
  title: string;
  subtitle: string;
  welcome: string;
  disclaimer: string;
  inputPlaceholder: string;
  inputAriaLabel: string;
  sendAriaLabel: string;
  clearChat: string;
  minimize: string;
  minimizeChat: string;
  openChat: string;
  chatDialog: string;
  thinking: string;
  analysing: string;
  generating: string;
  errorPrefix: string;
  today: string;
  yesterday: string;
}

export const en: ChatMessages = {
  title: "TEG AI Assistant",
  subtitle: "Ask me anything about TEG",
  welcome: "Hi! I'm the TEG assistant. How can I help you today?",
  disclaimer: "Responses generated by assistant might require verification.",
  inputPlaceholder: "Ask a question…",
  inputAriaLabel: "Message",
  sendAriaLabel: "Send",
  clearChat: "Clear chat",
  minimize: "Minimize",
  minimizeChat: "Minimize chat",
  openChat: "Open AI chat",
  chatDialog: "AI chat assistant",
  thinking: "Thinking...",
  analysing: "Analysing...",
  generating: "Generating response...",
  errorPrefix: "Error:",
  today: "Today",
  yesterday: "Yesterday",
};
