export const en = {
  title: "TEG AI Assistant",
  subtitle: "Ask me anything about TEG",
  welcome: "Hi! I'm the TEG assistant. How can I help you today?",
  suggestions: [
    "What is TEG?",
    "What exam levels are available?",
    "How do I contact TEG?",
  ],
  disclaimer: "Responses generated by assistant might require verification.",
  inputPlaceholder: "Ask a question…",
  inputAriaLabel: "Message",
  sendAriaLabel: "Send",
  clearChat: "Clear chat",
  minimize: "Minimize",
  minimizeChat: "Minimize chat",
  openChat: "Open AI chat",
  chatDialog: "AI chat assistant",
  thinking: "Thinking...",
  analysing: "Analysing...",
  generating: "Generating response...",
  errorPrefix: "Error:",
  today: "Today",
  yesterday: "Yesterday",
} as const;

export type ChatMessages = typeof en;
